---
abstract: 'Moose-ified TT Template Classes for applying traits'
author:
  - 'Caleb Cushing <xenoterracide@gmail.com>'
build_requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
  perl: 5.004
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101582, CPAN::Meta::Converter version 2.101591'
license: artistic2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Template
requires:
  Moose: 0
  Template: 0
  Template::Context: 0
  namespace::autoclean: 0
resources:
  bugtracker: http://github.com/xenoterracide/MooseX-Template/issues
  repository: git://github.com/xenoterracide/MooseX-Template.git
version: 0.01
